export * from './source/log.ts'
export * from './source/build.ts'
export * from './source/pathlib.ts'
export * from './source/platform.ts'
export * from './source/shell.ts'
export { autoReadFile, exit } from './source/utils.ts'
